version: 2.1

jobs:
    build:
        docker: # use the docker executor type; machine and macos executors are also supported
            - image: cimg/base:2022.03 # the primary container, where your job's commands are run
        steps:
            - checkout
            - run:  git submodule update --init --recursive
            # .net install - This seems like it would be better suited to be an orb?
            - run:
                name: Install .net sdk
                command: | 
                    wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
                    sudo dpkg -i packages-microsoft-prod.deb
                    rm packages-microsoft-prod.deb
                    sudo apt-get update
                    sudo apt-get install -y apt-transport-https
                    sudo apt-get update
                    sudo apt-get install -y dotnet-sdk-6.0                    





workflows:
    build-workflow:
        jobs:
            - build